### ISSUE TITLE
Change main branch to “gh-pages”

### ISSUE THREAD

**Issue by tripu** [w3c/manual-of-style#2]
&hellip;and get rid of `master`, so that [`w3c.github.io/manual-of-style`](https://w3c.github.io/manual-of-style/) works, as suggested in a8766c52c592886d027cdffedf81b82ed0ba3feb.

**Comment by sideshowbarker** [comment]
Isn’t the repo is already set up to mirror from master to https://w3c.github.io/manual-of-style/ ?

https://w3c.github.io/manual-of-style/Overview.html works at least.

I think the only reason https://w3c.github.io/manual-of-style/ by itself doesn’t is because github only does that if the filename is `index.html`.

**Comment by tripu** [comment]
Oh. I missed [the news](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages). It used to be that only `gh-pages` could be served like that. OK, then :)
