### ISSUE TITLE
RFC2119 keywords are not in uppercase

### ISSUE THREAD

**Issue by halindrome** [w3c/manual-of-style#3]
Section 10 indicates that RFC2119 keywords should be presented in uppercase and bold.  However, recent changes to ReSpec mean this is not the case in this document (which is based upon ReSpec), nor in other ReSpec generated documents.

**Comment by dbooth-boston** [comment]
As an example of this problem, the source text of the Manual of Style in section 10 (line 678) says:
https://github.com/w3c/manual-of-style/blob/7ca494432ad437ed78b93acb28ecd71263506e4f/index.html#L678
```
(<span class="not-en">e.g.</span>, "MUST", "MUST NOT", "REQUIRED").</p>
```

But those RFC2119 keywords currently render in the browser as red lowercase:
![Image of RFC2119 keywords in browser](https://lists.w3.org/Archives/Public/www-archive/2017Sep/att-0004/Screenshot_from_2017-09-25_09-49-42.png)

This appears to be a bug in ReSpec, because it is not correctly implementing the W3C Manual of Style.  But because the Manual of Style is using ReSpec, the bug causes the above example in the Manual of Style to be rendered incorrectly, which misleads readers into thinking that RFC2119 keywords are supposed to be rendered in lower case.   I.e., it sets a wrong example.

**Comment by svgeesus** [comment]
The manual of style was not actually using the markup (`code` element, class of `rfc2119`) which it recommended.
Fixed by https://github.com/w3c/manual-of-style/commit/634743af9632129f290429c4f922e0364fa2cae2

**Comment by sideshowbarker** [comment]
What the style manual should rightly say here instead is, never use RFC 2119 keyword in non-normative text. If editors ensure they’re always using RFC 2119 keywords normatively, then for readers of the spec who see an RFC 2119 keyword in a sentence, it’s unambiguous whether or not the word is being used in the RFC 2119 sense.

It’s not difficult for editors to write specs in such a way that all the RFC 2119 keywords are only used normatively. We have lots of specs that are already consistently written that way. It’s even possible to do automated linting to catch some non-normative misuses of RFC 2119 keywords:

https://github.com/whatwg/html-build/blob/master/lint.sh#L17-L18

```bash
  perl -ne '$/ = "\n\n"; print "$_" if (/class="?(note|example).+(\n.+)*\s+(should|must|may|optional|recommended)(\s|$)/mi)' "$1" | perl -lpe 'print "\nRFC2119 keyword in example or note (use: might, can, has to, or override with <!--non-normative-->must):" if $. == 1'
  perl -ne '$line++; $in_domintro = 1 if (/^  <dl class="domintro">$/); print "$line: $_" if ($in_domintro && /\s+(should|must|may|optional|recommended)(\s|$)/i); $in_domintro = 0 if (/^  <\/dl>$/)' "$1" | perl -lpe 'print "\nRFC2119 keyword in domintro (use: might, can, has to, or override with <!--non-normative-->must):" if $. == 1'
```

**Comment by dbooth-boston** [comment]
I fully agree with that rule -- to never use an RFC 2119 keyword in non-normative text -- but even if that rule were consistently followed it still does not eliminate the need to render 2219 keywords in a way that gives the reader a clear visual cue about their special meaning, for a couple of reasons.  For one, without carefully examining the whole document for its usage of 2119 keywords, the reader won't know whether the spec writers have been that careful, and readers just aren't going to do that analysis.  And for another, spec readers frequently jump directly to a particular section (from a web search, for example) to look things up, rather than reading linearly from the beginning, where 2119 adherence is specified.  Special rendering helps to alert the reader.
